#!/bin/sh

USER="jasper"

case "$1" in
   start)
      cd /opt/jasper/jasper-2.1.0/jsb-core/mule-standalone-3.4.0/bin
      su "$USER" -c "./mule start"
      cd ../../../
      ;;
   stop)
      # No-op
      ;;
   restart|reload|force-reload)
      # No-op
      ;;
   *)
      # No-op
      ;;
esac
exit 0
