#!/bin/bash

USER="jasper"

case "$1" in
    start)
      cd /opt/jasper/jasper-2.1/jsb-core/bin
      su "$USER" -c "./jsb start"
      cd ..
      ;;
   stop)
      # No-op
      ;;
   restart|reload|force-reload)
      # No-op
      ;;
   *)
      # No-op
      ;;
esac
exit 0
