#!/bin/sh
JSB_CLASSPATH=/opt/jasper/jasper-1.1/jsb-core/jars/*:/opt/jasper/jasper-1.1/jsb-core/3rdParty/*
JSB_PROPERTY_FILE=/opt/jasper/jasper-1.1/jsb-core/config/jsb.properties
JSB_KEYSTORE=/opt/jasper/jasper-1.1/jsb-core/keystore/
JSB_LOG4J_XML=/opt/jasper/jasper-1.1/jsb-core/config/jsb-log4j.xml
JSB_MAIN_CLASS=org.jasper.jCore.engine.JECore

case "$1" in
    start)
      cd /opt/jasper/jasper-1.1/jsb-core
      java -ea -Djsb-property-file=$JSB_PROPERTY_FILE -Djsb-keystore=$JSB_KEYSTORE -Djsb-log4j-xml=$JSB_LOG4J_XML -classpath $JSB_CLASSPATH $JSB_MAIN_CLASS &
      ;;
   stop)
      # No-op
      ;;
   restart|reload|force-reload)
      # No-op
      ;;
   *)
      # No-op
      ;;
esac
exit 0
